#!/bin/sh
#
# pgcheck		Start pgcheck
#
# chkconfig: 345 98 05
# description: Tool for checking health of PostgreSQL databases from PL\Proxy hosts
# processname: pgcheck.py
# pidfile: /var/run/pgcheck/pgcheck.pid


# Source function library
. /etc/init.d/functions

RETVAL=0


PATH=/bin:/sbin:/usr/bin:/usr/sbin
prog="/usr/bin/pgcheck"
config=/etc/pgcheck.conf
user=`awk '/^daemon_user/ {print $NF}' $config`

start()
{
	echo -n $"Starting pgcheck:"

	if [ "$(pidofproc $prog)" = "" ]; then
		daemon --user=$user $prog #>/dev/null 2>&1
		success
		echo
	else
		failure
		echo
	fi
}


stop()
{
	echo -n $"Stopping pgcheck: "
	killproc $prog
	echo
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
	stop
	sleep 1
	start
	;;
  status)
        status $prog
	RETVAL=$?
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit $RETVAL

